default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: "root"
  password: "Gioyeula1."
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: shop

test:
  <<: *default
  database: shop

production:
  <<: *default
  database: shop
