# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e955b795875b7d525b049acfb67769dbd2fc85903f39bbfc2b1e04d805ca1c1245ecb0c29e86d6407c5831e0195a8abb5012c5e5bf830a6332b148bc78f031b

test:
  secret_key_base: 85100c63996f54233d8996cd317a0efc9e4db93f6f106a19f57810d4060d9664a5ff6e91d768d24b92681c971c7b7053aa4be9f0a616dce530ee435960c5d155

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
